function JB3T = body_jacobian3_T(th1,th2,th3,l1,l2,l3)
%PA3L_BODYJAC3_T
%    Computes transpos of the body Jacobian at the third link CoM.
%    JB3T = PA3L_BODYJAC3_T(TH1,TH2,TH3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Jul-2020 11:25:30

t2 = conj(th2);
t3 = conj(th3);
t4 = sin(t2);
t5 = cos(t2);
t6 = sin(t3);
t7 = conj(l1);
t8 = conj(l2);
t9 = cos(t3);
t10 = conj(l3);
t11 = t10./2.0;
t12 = t7+t8+t11;
t13 = t7+t8;
t14 = t6.*t12;
t22 = t6.*t13;
t15 = t14-t22;
t16 = t9.*t12;
t17 = t9-1.0;
t24 = t13.*t17;
t18 = t16-t24;
t19 = t5.*t6;
t20 = t4.*t9;
t21 = t19+t20;
t23 = t5.*t15;
t25 = t4.*t18;
t26 = t4.*t6;
t27 = t4.*t15;
t28 = t5-1.0;
t29 = t7.*t28;
JB3T = reshape([(t26-t5.*t9).*(t23+t25-t4.*t7)-t21.*(t27+t29-t5.*t18),-t6.*t7+t6.*t18-t9.*t15,0.0,(t26-t5.*t9).*(t27+t29-t5.*t18)+t21.*(t23+t25-t4.*t7),-t7.*t9+t9.*t18+t6.*(t14-t22),t11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0],[3,6]);
