function N = gravity_vector(th1,th2,th3,g,l1,l2,l3,m1,m2,m3)
%PA3L_GRAVITYVECTOR
%    N = PA3L_GRAVITYVECTOR(TH1,TH1D,TH2,TH2D,TH3,TH3D,G,L1,L2,L3,M1,M2,M3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Jul-2020 11:25:04

t2 = th1+th2;
t3 = cos(t2);
t4 = cos(th1);
t5 = l1.*t4;
t6 = l2.*t3;
t7 = th1+th2+th3;
t8 = cos(t7);
t9 = (l3.*t8)./2.0;
N = [g.*m2.*(t5+(l2.*t3)./2.0)+g.*m3.*(t5+t6+t9)+(g.*l1.*m1.*t4)./2.0;g.*m3.*(t6+t9)+(g.*l2.*m2.*t3)./2.0;(g.*l3.*m3.*t8)./2.0];
