function link1 = link1(th1,th2,th3,l1,l2,l3)
%PA3L_LINK1
%    LINK1 = PA3L_LINK1(TH1,TH2,TH3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Jul-2020 11:25:30

link1 = [l1.*cos(th1);l1.*sin(th1)];
