function link2 = link2(th1,th2,th3,l1,l2,l3)
%PA3L_LINK2
%    LINK2 = PA3L_LINK2(TH1,TH2,TH3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Jul-2020 11:25:30

t2 = th1+th2;
link2 = [l2.*cos(t2)+l1.*cos(th1);l2.*sin(t2)+l1.*sin(th1)];
